const CREATE = "CREATE";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const FETCH_ALL = "FETCH_ALL";
const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";

const AUTH = "AUTH";
const LOGOUT = "LOGOUT";

const START_LOADING = "STARTING_LOADING";
const END_LOADING = "ENDING_LOADING";

export {
  AUTH,
  CREATE,
  DELETE,
  END_LOADING,
  FETCH_ALL,
  FETCH_BY_SEARCH,
  LOGOUT,
  START_LOADING,
  UPDATE,
};
